### ISSUE TITLE
error occurs in v0.10

### ISSUE THREAD

**Issue by dexter-hwang** [conduktor/kafka-security-manager#103]
v0.9-release
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:v0.9-release

...return acl data. no error :) 
```

v0.10.2-release
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:v0.10.2-release

Exception in thread "main" com.typesafe.config.ConfigException$WrongType: application.conf @ jar:file:/opt/docker/lib/com.github.conduktor.ksm.kafka-security-manager-0.10.jar!/application.conf: 9: extract has type OBJECT rather than BOOLEAN
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.github.conduktor.ksm.AppConfig$KSM$.<init>(AppConfig.scala:62)
        at com.github.conduktor.ksm.AppConfig.KSM$lzycompute$1(AppConfig.scala:58)
        at com.github.conduktor.ksm.AppConfig.KSM(AppConfig.scala:58)
        at com.github.conduktor.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$conduktor$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:22)
        at com.github.conduktor.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:10)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at com.github.conduktor.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:10)
        at com.github.conduktor.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)
```

latest
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:latest
Exception in thread "main" com.typesafe.config.ConfigException$WrongType: application.conf @ jar:file:/opt/docker/lib/com.github.conduktor.ksm.kafka-security-manager-0.11.0-SNAPSHOT.jar!/application.conf: 9: extract has type OBJECT rather than BOOLEAN
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.github.conduktor.ksm.AppConfig$KSM$.<init>(AppConfig.scala:62)
        at com.github.conduktor.ksm.AppConfig.KSM$lzycompute$1(AppConfig.scala:58)
        at com.github.conduktor.ksm.AppConfig.KSM(AppConfig.scala:58)
        at com.github.conduktor.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$conduktor$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:22)
        at com.github.conduktor.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:10)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at com.github.conduktor.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:10)
        at com.github.conduktor.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)

```

**Comment by simplesteph** [comment]
@ntrp can you please check ? Is this related to your latest PR ?
